### ISSUE TITLE
Not working on windows with latest release

### ISSUE THREAD

**Issue by fgma** [neilpa/yajsv#1]
Running 

> ./yajsv.windows.amd64.exe -s my.schema.json data.json

results in an error on windows:

> .../my.schema.json: invalid schema: parse file://...\my.schema.json: invalid character "\\" in host name

Seems like path handling is broken somehow on windows.

**Comment by neilpa** [comment]
Thanks for the bug report. I've only used this on Unix-based OSs so far. Hopefully this is only a problem with my wrapper and not the underlying json schema validation library. The former will be a lot easier to track and fix.

**Comment by neilpa** [comment]
Yea, the problem is [here](https://github.com/neilpa/yajsv/blob/faf5a6353759579648cba80db8d72e6905a082cd/main.go#L181-L187) when converting to file URIs. Looks like [Windows requires some special case handling](https://docs.microsoft.com/en-us/archive/blogs/ie/file-uris-in-windows).

**Comment by fgma** [comment]
Are you going to fix this or do you need some help?

**Comment by neilpa** [comment]
I'm open to a PR if you'd like to contribute, otherwise I'm not sure when I'll get around to it. I've got access to a Win10 box but rarely use it and haven't done any go dev on it.
