### ISSUE TITLE
support self signed certs

### ISSUE THREAD

**Issue by zendril** [neilpa/yajsv#11]
Resolving schema from site with self-signed certs (which we certainly have a bunch of those inside a big enterprise) results in this error:

```
invalid schema: invalid character '<' looking for beginning of value
```

Is there an option on the underlying go library to accept self-signed certs and can we add that as a flag to yajsv?

**Comment by zendril** [comment]
@neilpa Started using yajsv in anger.. and got the point where I'm using refs.
The local refs `-r` work fine, but resolving from a site with self-signed certs has the error above.

**Comment by neilpa** [comment]
> Is there an option on the underlying go library to accept self-signed certs

I'd assume so but don't know. I've not had to go down this route with go.

> can we add that as a flag to yajsv?

Do you have examples of other tools in go that support something like this? I can see the need but I'm hesitant to add such a feature. I would rather rely on the system cert chain being the source of truth but can understand that this can be difficult. Alternatively, is it possible to reference these over old school `http`, especially if your confined to an internal enterprise network?

> The local refs -r work fine, but resolving from a site with self-signed certs has the error above.

I don't follow. Did you modify `yajsv` to also accept URIs from the command line as everything right now assumes it's a path on disk?

**Comment by zendril** [comment]
Did just a tiny bit more digging.

It looks like they may not have this implemented upstream on https://github.com/xeipuuv/gojsonschema/blob/master/jsonLoader.go

So I'll open an issue there.

Unfortunately, even moving to http just does a forced redirect back to https. In this case there is a self signed cert in the chain. Most of our tools (like java, etc.. ) have our CA imported which resolves the issue. Not sure if that is a thing with a pre-compiled go binary. I'll do some digging.

I did not modify yajsv to accept URIs..  
I made an assumption that yasjv is setting the ref to file:// when `-r` is passed in. From there I made the assupmtion/leap that this bit of code is being invoked which would then load the `$ref` from http: https://github.com/xeipuuv/gojsonschema/blob/master/jsonLoader.go#L146-L174

I'll go take a look at yajsv code again.. but maybe you'll know this right off hand quicker than I will.

**Comment by zendril** [comment]
Some good new for you: yajsv does appear to be able to pull schema refs from https.

I downloaded the kubernetes deployment schema: https://kubernetesjsonschema.dev/v1.14.2/deployment-apps-v1.json and saved it as deployment-apps-v1.json locally.

I created a sample deployment.yml file. 

I ran the following command:
`yajsv -s deployment-apps-v1.json deployment.yml`

Inside that primary schema is a reference to a **ton** of reference schemas needed to validate the yml document. They are loaded from https://kubernetesjsonschema.dev/v1.14.2/_definitions.json

That loaded fine and got back a pass.

So that it the good news. 
The bad news is that it does point back to the original question about how to support either a CA (which ours are added to the host chain I believe) or be able to pass in a flag to disable tls verify.

**Comment by neilpa** [comment]
> Some good new for you: yajsv does appear to be able to pull schema refs from https.
> ...
> That loaded fine and got back a pass.

Yea, the `-r` is for cases where the main schema doesn't explicitly reference the support schemas, e.g. local schemas. This is [similar to what `ajv-cli` does](https://github.com/jessedc/ajv-cli#-r---referenced-schemas). In the case where they are hosted somewhere they should be explicitly referenced by URL within the primary schema JSON. That's handled under the hood by `gojsonschema`.

> which ours are added to the host trust store I believe

If that's the case than it should just work without having to side-step TLS.

**Comment by neilpa** [comment]
https://golang.org/pkg/crypto/x509/

> On UNIX systems the environment variables SSL_CERT_FILE and SSL_CERT_DIR can be used to override the system default locations for the SSL certificate file and SSL certificate files directory, respectively.

**Comment by zendril** [comment]
yeah.. doing some more testing.. this *may* be because (for right now) it is hosted in a git repo that is protected.. i'll be this is actually because I can't pass in credentials..

**Comment by zendril** [comment]
I'm going to close this as I believe that is what the issue is.. and ultimately I'll move these schemas to an openly readable url.
