### ISSUE TITLE
provide an output for more details when verifying the file

### ISSUE THREAD

**Issue by Kreax** [neilpa/yajsv#15]
Hello, I'm using this tool, and I would like first to thank you for implementing it, it is very useful.

I would find it very useful too and output that indicates the place where the error when verifications happen to make the correction of the JSON easier. 

it should look likes something like this : 

> line 36: property "name" is missing 

it would be a very cool feature! maybe enabling it with a "verbose" flag

thank you for your attention!

**Comment by neilpa** [comment]
`yajsv` is mostly a wrapper around [xeipuuv/gojsonschema](https://github.com/xeipuuv/gojsonschema) which handles the actual validation. The messages displayed come directly from that library. See https://github.com/xeipuuv/gojsonschema/issues/185 for some discussion around the error messages and potentially including line numbers.

**Comment by gbburkhardt** [comment]
Would really like to have line numbers with the error messages.  It would be really helpful.  Thanks!
